name: Run JMeter Test with Allure

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clean Previous Reports
        run: |
          echo "Cleaning previous reports..."
          rm -rf allure-results
          rm -rf allure-report
          rm -rf artifacts
          rm -f *.jtl
          rm -f jmeter.log

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Taurus
        run: pip install bzt

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.34.1.tgz
          tar -xzf allure-2.34.1.tgz
          echo "$PWD/allure-2.34.1/bin" >> $GITHUB_PATH

      - name: Run JMeter Test
        run: |
          bzt Krofturg.jmx

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
