name: Run JMeter Test with Taurus

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install Taurus
        run: |
          pip install bzt

      - name: Run JMeter Test
        run: |
          bzt Krofturg.jmx

      - name: Upload Taurus Report
        uses: actions/upload-artifact@v4
        with:
          name: taurus-report
          path: artifacts/
